<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Namoyish etilayabdi <b>{begin, number}-{end, number}</b> ta yozuv <b>{totalCount, number}</b> {totalCount, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Jami <b>{count, number}</b> {count, plural, one{{item}} few{{items-few}} many{{items-many}} other{{items}}}.',
    'item' => 'qayd',
    'items' => 'yozuv',
    'items-few' => 'yozuv',
    'items-many' => 'yozuv',
    '<small>Loading &hellip;</small>' => 'Yuklanmoqda &hellip;',
    'Actions' => 'Amallar',
    'Active' => 'Aktiv',
    'Add Book' => 'Kitob qo\'shish',
    'All' => 'Barchasi',
    'Are you sure to delete this {item}?' => '{item}\'ni o\'chirishga ishonchingiz komilmi?',
    'Book Listing' => 'Kitoblar ro\'yxati',
    'CSV' => '',
    'Clear selection' => 'Tozalash',
    'Collapse' => '',
    'Collapse All' => '',
    'Comma Separated Values' => '',
    'Delete' => 'O\'chirish',
    'Disable any popup blockers in your browser to ensure proper download.' => 'To\'g\'ri yuklab olishni ta\'minlash uchun brauzeringizdagi popup blokerlarini o\'chirib qo\'ying.',
    'Download Selected' => 'Tanlanganlarni yuklab olish',
    'Excel' => '',
    'Expand' => '',
    'Expand All' => '',
    'Export' => 'Eksport',
    'Export All Data' => 'Barcha ma\'lumot eksport qilish',
    'Export Page Data' => 'Sahifadagi barcha ma\'lumotni eksport qilish',
    'ExportWorksheet' => '',
    'Failed to update editable data due to an unknown server error' => 'No\'malum sababga ko\'ra saqlab bo\'lmadi',
    'Generated' => 'Yaratildi',
    'Generating the export file. Please wait...' => 'Eksport uchun fayllar yaratilmoqda. Iltimos kuting...',
    'Grid Export' => 'Grid Eksport',
    'HTML' => '',
    'Hyper Text Markup Language' => 'Giper matinli markerlash tili',
    'Inactive' => 'Aktiv emas',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'JSON' => '',
    'JavaScript Object Notation' => '',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Library' => '',
    'Microsoft Excel 95+' => '',
    'No data found' => '',
    'No valid editable model found' => '',
    'Ok to proceed?' => '',
    'PDF' => '',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => 'Sahifa',
    'Portable Document Format' => '',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => '',
    'Reset Grid' => '',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'Show all data' => 'Barchasini ko\'rsatish',
    'Show first page data' => '',
    'Tab Delimited Text' => '',
    'Text' => 'Matn',
    'The CSV export file will be generated for download.' => '',
    'The EXCEL export file will be generated for download.' => '',
    'The HTML export file will be generated for download.' => '',
    'The JSON export file will be generated for download.' => '',
    'The PDF export file will be generated for download.' => '',
    'The TEXT export file will be generated for download.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'There are {totalCount} records. Are you sure you want to display them all?' => '',
    'Update' => 'Yangilash',
    'View' => 'Ko\'rinish',
    'Yii2 Grid Export (PDF)' => '',
    'export' => '',
    'grid-export' => '',
    'items-acc' => '',
    'krajee, grid, export, yii2-grid, pdf' => '',
    '© Krajee Yii2 Extensions' => '',
];
